# Generated by Django 3.1.4 on 2020-12-14 02:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_category', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], max_length=50)),
                ('meal_description', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealtrack', to='CT.client')),
            ],
        ),
    ]
