# Generated by Django 3.1.1 on 2020-12-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CT', '0002_mealtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mealtracker',
            name='meal_category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=50),
        ),
    ]
