# Generated by Django 3.1.1 on 2020-12-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CT', '0003_auto_20201214_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='BMR',
            field=models.DecimalField(decimal_places=2, default=2008.1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='client_age',
            field=models.IntegerField(default=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=60, max_length=50),
            preserve_default=False,
        ),
    ]
